site_name: Commandes Linux
repo_url: https://github.com/phorcys420/commandes-linux

nav:
  - Accueil: index.md
  - Système de fichiers:
    - Opérations de fichiers: fs/files.md
  - Utilisateurs: users.md
  - Groupes: groups.md

theme:
  language: fr
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    scheme: slate
    primary: red
    accent: deep orange

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - content.tabs.link
    - toc.follow

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - md_in_html
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true

extra:
  generator: false